# Copyright 2019-2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2

---
minimum_pre_commit_version: 1.12.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
        description: Check for files that contain merge conflict strings.
        language_version: python3
      - id: trailing-whitespace
        description: Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
        language_version: python3
      - id: mixed-line-ending
        description: Replaces or checks mixed line ending.
        args: [--fix=lf]
        language_version: python3
      - id: fix-byte-order-marker
        description: Removes UTF-8 BOM if present, generally a Windows problem.
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline.
        language_version: python3
        exclude: '^README*'
      - id: check-ast
        description: Simply check whether files parse as valid python.
        language_version: python3
      - id: check-yaml
      - id: check-json
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck -x
        language: system
        types: [shell]
